version: '3.8'

services:
  # =====================
  # Bases de données
  # =====================
  
  # PostgreSQL pour User Service
  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
    ports:
      - "5439:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  # PostgreSQL pour Account Service
  account-db:
    image: postgres:17
    container_name: account-db
    environment:
      POSTGRES_DB: account_service_db
      POSTGRES_USER: account_admin
      POSTGRES_PASSWORD: account_password
    ports:
      - "5438:5432"
    volumes:
      - account-data:/var/lib/postgresql/data

  
  # =====================
  # Services d'infrastructure
  # =====================

  # Discovery Service (Eureka)
  discovery-service:
    image: openjdk:17-jdk-slim
    container_name: discovery-service
    build: ./discovery-service
    environment:
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-service/target:/tmp  # Assurez-vous que c'est le bon chemin
    working_dir: /tmp
    command: ["java", "-jar", "discovery-service.jar"]
    networks:
      - microservices-network

  # Config Service
  config-service:
    image: openjdk:17-jdk-slim
    container_name: config-service
    environment:
      - SPRING_APPLICATION_NAME=config-service
      - SERVER_PORT=8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8888:8888"
    volumes:
      - ./config-service/target:/tmp  # Assurez-vous que le fichier JAR est dans le dossier target
    working_dir: /tmp
    command: ["java", "-jar", "config-service.jar"]
    depends_on:
      - discovery-service
    networks:
      - microservices-network

  # Gateway API
  gateway-service:
    image: openjdk:17-jdk-slim
    container_name: gateway-service
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SERVER_PORT=9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "9999:8080"
    volumes:
      - ./gateway-service/target:/tmp
    working_dir: /app
    command: ["java", "-jar", "gateway-service.jar"]
    depends_on:
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # =====================
  # Microservices
  # =====================

  # User Service
  user-service:
    image: openjdk:17-jdk-slim
    container_name: user-service
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_service_db
      - SPRING_DATASOURCE_USERNAME=user_admin
      - SPRING_DATASOURCE_PASSWORD=user_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8081:8081"
    volumes:
      - ./user-service/target:/tmp
    depends_on:
      - user-db
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # Account Service
  account-service:
    image: openjdk:17-jdk-slim
    container_name: account-service
    environment:
      - SPRING_APPLICATION_NAME=account-service
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-db:5432/account_service_db
      - SPRING_DATASOURCE_USERNAME=account_admin
      - SPRING_DATASOURCE_PASSWORD=account_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8082:8082"
    volumes:
      - ./account-service/target:/tmp
    depends_on:
      - account-db
      - discovery-service
      - config-service
    networks:
      - microservices-network


volumes:
  user-data:
  account-data:

networks:
  microservices-network:
    driver: bridge
