version: '3.8'

services:
  # =====================
  # Bases de données
  # =====================
  
  # PostgreSQL pour User Service
  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
    ports:
      - "5439:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  # PostgreSQL pour Account Service
  account-db:
    image: postgres:17
    container_name: account-db
    environment:
      POSTGRES_DB: account_service_db
      POSTGRES_USER: account_admin
      POSTGRES_PASSWORD: account_password
    ports:
      - "5438:5432"
    volumes:
      - account-data:/var/lib/postgresql/data

  # PostgreSQL pour Notification Service
  notification-db:
    image: postgres:17
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_service_db
      POSTGRES_USER: notification_admin
      POSTGRES_PASSWORD: notification_password
    ports:
      - "5434:5432"
    volumes:
      - notification-data:/var/lib/postgresql/data

  # PostgreSQL pour Transaction Service
  transaction-db:
    image: postgres:17
    container_name: transaction-db
    environment:
      POSTGRES_DB: transaction_service_db
      POSTGRES_USER: transaction_admin
      POSTGRES_PASSWORD: transaction_password
    ports:
      - "5435:5432"
    volumes:
      - transaction-data:/var/lib/postgresql/data

  # PostgreSQL pour Loan Service
  loan-db:
    image: postgres:17
    container_name: loan-db
    environment:
      POSTGRES_DB: loan_service_db
      POSTGRES_USER: loan_admin
      POSTGRES_PASSWORD: loan_password
    ports:
      - "5436:5432"
    volumes:
      - loan-data:/var/lib/postgresql/data

  # =====================
  # Services d'infrastructure
  # =====================

  # Discovery Service (Eureka)
  discovery-service:
    image: openjdk:17-jdk-slim
    container_name: discovery-service
    build: ./discovery-service
    environment:
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-service/target:/app  # Assurez-vous que c'est le bon chemin
    working_dir: /app
    command: ["java", "-jar", "discovery-service.jar"]
    networks:
      - microservices-network

  # Config Service
  config-service:
    image: openjdk:17-jdk-slim
    container_name: config-service
    environment:
      - SPRING_APPLICATION_NAME=config-service
      - SERVER_PORT=8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8888:8888"
    volumes:
      - ./config-service/target:/app  # Assurez-vous que le fichier JAR est dans le dossier target
    working_dir: /app
    command: ["java", "-jar", "config-service.jar"]
    depends_on:
      - discovery-service
    networks:
      - microservices-network

  # Gateway API
  gateway-service:
    image: openjdk:17-jdk-slim
    container_name: gateway-service
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SERVER_PORT=9999
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "9999:8080"
    volumes:
      - ./gateway-service/target:/app
    working_dir: /app
    command: ["java", "-jar", "gateway-service.jar"]
    depends_on:
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # =====================
  # Microservices
  # =====================

  # User Service
  user-service:
    image: openjdk:17-jdk-slim
    container_name: user-service
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_service_db
      - SPRING_DATASOURCE_USERNAME=user_admin
      - SPRING_DATASOURCE_PASSWORD=user_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8081:8081"
    volumes:
      - ./user-service/target:/app
    depends_on:
      - user-db
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # Account Service
  account-service:
    image: openjdk:17-jdk-slim
    container_name: account-service
    environment:
      - SPRING_APPLICATION_NAME=account-service
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-db:5432/account_service_db
      - SPRING_DATASOURCE_USERNAME=account_admin
      - SPRING_DATASOURCE_PASSWORD=account_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8082:8082"
    volumes:
      - ./account-service/target:/app
    depends_on:
      - account-db
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # Notification Service
  notification-service:
    image: openjdk:17-jdk-slim
    container_name: notification-service
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-db:5432/notification_service_db
      - SPRING_DATASOURCE_USERNAME=notification_admin
      - SPRING_DATASOURCE_PASSWORD=notification_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8083:8083"
    volumes:
      - ./notification-service/target:/app
    depends_on:
      - notification-db
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # Transaction Service
  transaction-service:
    image: openjdk:17-jdk-slim
    container_name: transaction-service
    environment:
      - SPRING_APPLICATION_NAME=transaction-service
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://transaction-db:5432/transaction-service_db
      - SPRING_DATASOURCE_USERNAME=transaction_admin
      - SPRING_DATASOURCE_PASSWORD=transaction_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8084:8084"
    volumes:
      - ./transaction-service/target:/app
    depends_on:
      - transaction-db
      - discovery-service
      - config-service
    networks:
      - microservices-network

  # Loan Service
  loan-service:
    image: openjdk:17-jdk-slim
    container_name: loan-service
    environment:
      - SPRING_APPLICATION_NAME=loan-service
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://loan-db:5432/loan-service_db
      - SPRING_DATASOURCE_USERNAME=loan_admin
      - SPRING_DATASOURCE_PASSWORD=loan_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    ports:
      - "8085:8085"
    volumes:
      - ./loan-service/target:/app
    depends_on:
      - loan-db
      - discovery-service
      - config-service
    networks:
      - microservices-network

volumes:
  user-data:
  account-data:
  notification-data:
  transaction-data:
  loan-data:

networks:
  microservices-network:
    driver: bridge
