version: '3.8'

services:
  # Base de données pour user-service
  postgres-user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: userdbuser
      POSTGRES_PASSWORD: userdbpassword
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  # Base de données pour account-service
  postgres-account-db:
    image: postgres:13
    environment:
      POSTGRES_USER: accountdbuser
      POSTGRES_PASSWORD: accountdbpassword
      POSTGRES_DB: accountdb
    ports:
      - "5433:5432"
    volumes:
      - account-db-data:/var/lib/postgresql/data

  # Base de données pour loan-service
  postgres-loan-db:
    image: postgres:13
    environment:
      POSTGRES_USER: loandbuser
      POSTGRES_PASSWORD: loandbpassword
      POSTGRES_DB: loandb
    ports:
      - "5434:5432"
    volumes:
      - loan-db-data:/var/lib/postgresql/data

  # Base de données pour transaction-service
  postgres-transaction-db:
    image: postgres:13
    environment:
      POSTGRES_USER: transactiondbuser
      POSTGRES_PASSWORD: transactiondbpassword
      POSTGRES_DB: transactiondb
    ports:
      - "5435:5432"
    volumes:
      - transaction-db-data:/var/lib/postgresql/data

  # Base de données pour notification-service
  postgres-notification-db:
    image: postgres:13
    environment:
      POSTGRES_USER: notificationdbuser
      POSTGRES_PASSWORD: notificationdbpassword
      POSTGRES_DB: notificationdb
    ports:
      - "5436:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  # User Service
  user-service:
    build: ./user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: userdbuser
      SPRING_DATASOURCE_PASSWORD: userdbpassword
    depends_on:
      - postgres-user-db
    ports:
      - "8081:8081"

  # Account Service
  account-service:
    build: ./account-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-account-db:5432/accountdb
      SPRING_DATASOURCE_USERNAME: accountdbuser
      SPRING_DATASOURCE_PASSWORD: accountdbpassword
    depends_on:
      - postgres-account-db
    ports:
      - "8082:8082"

  # Loan Service
  loan-service:
    build: ./loan-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-loan-db:5432/loandb
      SPRING_DATASOURCE_USERNAME: loandbuser
      SPRING_DATASOURCE_PASSWORD: loandbpassword
    depends_on:
      - postgres-loan-db
    ports:
      - "8083:8083"

  # Transaction Service
  transaction-service:
    build: ./transaction-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-transaction-db:5432/transactiondb
      SPRING_DATASOURCE_USERNAME: transactiondbuser
      SPRING_DATASOURCE_PASSWORD: transactiondbpassword
    depends_on:
      - postgres-transaction-db
    ports:
      - "8084:8084"

  # Notification Service
  notification-service:
    build: ./notification-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notification-db:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: notificationdbuser
      SPRING_DATASOURCE_PASSWORD: notificationdbpassword
    depends_on:
      - postgres-notification-db
    ports:
      - "8085:8085"

# Définir les volumes à l'extérieur de la section "services"
volumes:
  user-db-data:
  account-db-data:
  loan-db-data:
  transaction-db-data:
  notification-db-data: